const EMPLOYEES = {
  LOAD: "EMPLOYEES_LOAD",
  POST_SUCCESS: "POST_SUCCESS",
  POST_EMPLOYEE: "POST_EMPLOYEE",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  LOAD_SUCCESS: "EMPLOYEES_LOAD_SUCCESS",
  LOAD_FAILED: "EMPLOYEES_LOAD_FAILED",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  REDIRECT: "REDIRECT",
};

export default EMPLOYEES;
